---
version: "3.7"

services:
  collabora:
    image: collabora/code:23.05.1.2.1
    environment:
      aliasgroup1: https://172.17.0.1:6789 # allow to contact WOPI server on this address
      domain: localhost
      extra_params: --o:ssl.enable=false --o:ssl.termination=false --o:net.frame_ancestors=localhost:*
    cap_add:
      - MKNOD
    ports:
      - 8080:9980
